### ISSUE TITLE
Windows Cookbook 1.37.0 breaks chef-client::task

### ISSUE THREAD

**Issue by ebrahim-moshaya** [opscode-cookbooks/chef-client#313]
All I have in my run list is chef-client::config and chef-client::task, with the attribute:
default['chef_client']['task']['frequency'] = 'onstart'
and the chef run fails. Note this was working fine with windows 1.36.6

================================================================================
 Error executing action `create` on resource 'windows_task[\chef-client]'
 ================================================================================

 NoMethodError
 -------------
 undefined method `password=' for Chef::Resource::WindowsTask

 Resource Declaration:
 ---------------------
 # In C:/tmp/kitchen/cache/cookbooks/chef-client/recipes/task.rb

  32: windows_task 'chef-client' do
  33:   run_level :highest
  34:   command "cmd /c '#{node['chef_client']['ruby_bin']} #{node['chef_client']['bin']} \
  35:   -L #{File.join(node['chef_client']['log_dir'], 'client.log')} \
  36:   -c #{File.join(node['chef_client']['conf_dir'], 'client.rb')} -s #{node['chef_client']['splay']} > NUL 2>&1'"
  37:
  38:   user               node['chef_client']['task']['user']
  39:   password           node['chef_client']['task']['password']
  40:   frequency          node['chef_client']['task']['frequency'].to_sym
  41:   frequency_modifier node['chef_client']['task']['frequency_modifier']
  42:   start_time         node['chef_client']['task']['start_time'] || start_time
  43: end

 Compiled Resource:
 ------------------
 # Declared in C:/tmp/kitchen/cache/cookbooks/chef-client/recipes/task.rb:32:in `from_file'

 windows_task("\chef-client") do
   action :create
   retries 0
   retry_delay 2
   default_guard_interpreter :default
   declared_type :windows_task
   cookbook_name "chef-client"
   recipe_name "task"
   run_level :highest
   command "cmd /c ' C:/opscode/chef/bin/chef-client   -L C:/chef/log/client.log   -c C:/chef/client.rb -s 300 > NUL 2>&1'"
   user "SYSTEM"
   frequency :onstart
   frequency_modifier 30
   task_name "\\chef-client"
 end

**Comment by jtimberman** [comment]
This is an issue in the [windows cookbook](https://github.com/opscode-cookbooks/windows/issues/219), which has a [PR open with a fix](https://github.com/opscode-cookbooks/windows/pull/220).
